<ul><li><a href="https://www.aasciences.ac.ke/">Home</a><ul><li><a href="https://www.aasciences.ac.ke/what-are-tags/">What are tags?</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/">About</a><ul><li><a href="https://www.aasciences.ac.ke/about/about-us/">About us</a><ul><li><a href="https://www.aasciences.ac.ke/about/about-us/about-the-aas/">About the AAS</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/about-us/history/">History</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/about-us/endowment-fund/">Endowment fund</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/about-us/mission-vision-and-strategy/">Mission, vision and strategy</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/about-us/achievements/">Achievements</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/about/our-organisation/">Our organisation</a><ul><li><a href="https://www.aasciences.ac.ke/about/our-organisation/governance/">Governance</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/our-organisation/staff/">Staff</a></li>
	<li><a href="https://www.aasciences.ac.ke/about/our-organisation/location/">Location</a></li>
	</ul></li>
	</li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/">Programmes</a><ul><li><a href="https://www.aasciences.ac.ke/programmes/circle/">Circle</a><ul><li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/">Climate Impact Research Capacity and Leadership Enhancement (CIRCLE)</a><ul><li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/key-elements-of-the-circle-programme/">Key elements of the CIRCLE programme</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/circle-provides-an-opportunity-for-a-ugandan-scientist-to-develop-his-career/">CIRCLE provides an opportunity for a Ugandan scientist to develop his career</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/circle-cvfs-cohort-1/">CIRCLE CVFs Cohort 1</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/circle-cvfs-cohort-2/">CIRCLE CVFs Cohort 2</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/how-participating-in-circle-has-won-one-fellow-big-grants/">How participating in CIRCLE has won one fellow big grants</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/guidance-for-circle-visiting-fellows-on-providing-access-to-research-data/">Guidance for CIRCLE Visiting Fellows on Providing Access to Research Data</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle/climate-impact-research-capacity-and-leadership-enhancement-circle/circle-open-access-publication-guidance/">CIRCLE Open Access Publication Guidance</a></li>
	</ul></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/easa/">AESA</a><ul><li><a href="https://www.aasciences.ac.ke/programmes/easa/alliance-for-accelerating-excellence-in-science-in-africa-aesa/">Alliance for Accelerating Excellence in Science in Africa (AESA)</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/cbrm/">CBRM</a><ul><li><a href="https://www.aasciences.ac.ke/programmes/cbrm/cell-biology-and-regenerative-medicine-research/">Cell Biology and Regenerative Medicine Research</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/science-equipment/">Science equipment</a><ul><li><a href="https://www.aasciences.ac.ke/programmes/science-equipment/science-equipment-policy-project/">Science Equipment Policy Project</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/deltas-calls-for-proposals/">DELTAS Africa calls for applications</a></li>
	<li><a href="https://www.aasciences.ac.ke/programmes/circle-field-stories/">CIRCLE field stories</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/recognising-excellence/">Recognising Excellence</a><ul><li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/">Recognising Excellence</a><ul><li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/the-aas-fellowships/">The AAS Fellowships</a><ul><li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/the-aas-fellowships/recognising-excellence-/">Fellows</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/the-aas-affiliates-programme/">The AAS Affiliates programme</a><ul><li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/the-aas-affiliates-programme/affiliates/">Affiliates</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/the-olusegun-obasanjo-prize/">The Olusegun Obasanjo Prize for Scientific Discovery and Technological Innovation</a><ul><li><a href="https://www.aasciences.ac.ke/recognising-excellence/recognising-excellence/the-olusegun-obasanjo-prize/the-olusegun-obasanjo-prize-for-scientific-discovery-and-technological-innovation/">The Olusegun Obasanjo Prize</a></li>
	</ul></li>
	</ul></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/calls-for-proposals/">Calls and Careers</a><ul><li><a href="https://www.aasciences.ac.ke/calls-for-proposals/calls/">Calls</a><ul><li><a href="https://www.aasciences.ac.ke/calls-for-proposals/calls/summer-school/">Summer school</a></li>
	<li><a href="https://www.aasciences.ac.ke/calls-for-proposals/calls/lindau-call-for-nominations/">Lindau call for nominations</a></li>
	<li><a href="https://www.aasciences.ac.ke/calls-for-proposals/calls/iso-lomso-fellowships/">Iso Lomso Fellowships</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/calls-for-proposals/careers/">Careers</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/updates/">Updates</a><ul><li><a href="https://www.aasciences.ac.ke/updates/blogs/">Blogs</a><ul><li><a href="https://www.aasciences.ac.ke/updates/blogs/deltas-africa-inception-meeting-/">DELTAS Africa inception meeting </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/blogs/a-new-way-of-supporting-research-outside-the-uk/">A new way of supporting research outside the UK</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/blogs/reflections-on-an-aas-staff-training-visit-to-london/">Reflections on an AAS staff training visit to London</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/blogs/how-to-write-a-fundable-research-proposal/">How to write a fundable research proposal</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/">Publications</a><ul><li><a href="https://www.aasciences.ac.ke/updates/publications/annual-reports/">Annual reports</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/sciencepolicyafrica/">Science *Policy* Africa</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/">Science </a><ul><li><a href="https://www.aasciences.ac.ke/updates/publications/science-/science-policy-africa-vol-20-no-4-december-2016/">Science *Policy* Africa Vol 20 No 4 December 2016</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-vol-20-no-3-september-2016/">Science*Policy*Africa Vol 20 No 3 September 2016</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-vol-20-no-2-june-2016/">Science*Policy*Africa Vol 20 No 2 June 2016</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-20-number-1-march-2016/">Science*Policy*Africa Volume 20 Number 1 March 2016</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-vol-19-no-4-january-2016/">Science*Policy*Africa Vol 19 No 4 January 2016</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-vol-19-no-3-sept-2015/">Science*Policy*Africa Vol 19 no 3 Sept 2015</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-19-no-2-july-2015/">Science*Policy*Africa Volume 19 No 2 July 2015</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-19-no-1-march-2015/">Science*Policy*Africa Volume 19 No 1 March 2015</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-18-no-4-2015/">Science*Policy*Africa Volume 18 No 4 January 2015</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-18-no-3-september-2014/">Science*Policy*Africa Volume 18 No 3 September 2014</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-18-no-2-june-2014/">Science*Policy*Africa Volume 18 No 2 June 2014</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-18-no-1-march-2014/">Science*Policy*Africa Volume 18 No 1 March 2014</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-17-no-4-december-2013/">Science*Policy*Africa Volume 17 No 4 December 2013</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-17-no-3-september-2013/">Science*Policy*Africa Volume 17 No 3 September 2013</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/publications/science-/sciencepolicyafrica-volume-17-no-2-june-2013/">Science*Policy*Africa Volume 17 No 2 June 2013</a></li>
	</ul></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/">News</a><ul><li><a href="https://www.aasciences.ac.ke/updates/news/africa-science-desk/">Africa Science Desk</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/call-to-support-the-creation-of-an-africa-synchrotron-project/">Call to support the creation of an Africa Synchrotron project</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/new-executive-director/">New Executive Director</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-elects-new-members-of-the-governing-council-/">AAS elects new members of the Governing Council </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/calls-to-endorse-african-space-sciences-initiative/">Calls to endorse African space sciences initiative</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/world-malaria-day-2010-podcast/">World Malaria Day 2017 Podcast</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/young-african-scholars-selected-to-attend-the-nobel-laureate-meetings/">Young African scholars selected to attend the Nobel Laureate meetings</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/african-academy-of-sciences-names-dr-tom-kariuki-interim-executive-director-/">African Academy of Sciences names Dr Tom Kariuki Interim Executive Director </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-affiliates-20172021/">Young African scientists recognised</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/santhes-thumbi-ndungu-wins-28-million-gilead-grant/">SANTHE's Thumbi Ndung'u wins $2.8 million Gilead grant</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/elizabeth-marincola-appointed-as-senior-advisor-for-communications-and-advocacy/">Elizabeth Marincola appointed Senior Advisor for Communications & Advocacy</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/precision-public-health-report/">Precision Public Health report</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aasamu-symposium-on-current-research-trends-in-mathematical-sciences-and-applications/">AAS/AMU Symposium on Current Research Trends in Mathematical Sciences</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/donation-us400000-from-kevin-marsh-winner-of-the-alsumait-prize/">Donation US$400,000 from Kevin Marsh, winner of the Al-Sumait Prize</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/launch-of-grand-challenges-africa-grants/">Launch of Grand Challenges Africa Grants</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-senior-adviser-wins-us-1-million-prize/">AAS Senior Adviser wins US$ 1 million prize</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/prof-makawiti-appointed-ag-treasurer-of-the-aas/">Prof Makawiti appointed Ag Treasurer of the AAS</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/collaborative-scientific-research-in-africa-/">Promoting collaborative research in Africa </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/professor-philippe-rasoanaivo-dies/">Professor Philippe Rasoanaivo dies</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/malagasy-researcher-is-winner-of-the-olusegun-obasanjo-science-prize/">Malagasy researcher wins the Olusegun Obasanjo Science prize</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/botswana-president-to-open-the-aas-10th-general-assembly-/">Botswana President to open the AAS 10th General Assembly </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/research-boost-creates-more-opportunities-for-african-scientists-/">Research boost creates more opportunities for African scientists </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-elected-an-executive-committee-member-of-the-iap/">AAS elected an executive committee member of the IAP</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/african-scientists-gather-for-grand-challenges-africa-meeting-to-guide-the-scientific-research-and-innovation-agenda-for-reaching-the-2030-sustainable-development-goals/">African scientists gather for Grand Challenges Africa Meeting </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/early-career-scientists-study-the-impact-of-climate-change-on-the-continent/">Early career scientists study the impact of climate change on the continent</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-develops-a-standard-for-good-financial-grant-practice/">AAS develops a standard for Good Financial Grant Practice</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/workshop-to-develop-a-pan-african-standard-for-gfgp/">Workshop to develop a pan African standard for GFGP</a></li>
	</li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-in-the-press/">AAS in the Press</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/seminar-on-developing-an-internationally-accepted-standard-for-good-financial-grant-practice/">Seminar on developing an internationally accepted standard for good financial grant practice</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-unveils-a-historical-mathematical-tool/">AAS unveils a historical mathematical tool</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-and-partners-to-launch-aesa-the-funding-platform-for-research/">AAS and partners to launch AESA, the funding platform for research</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/dr-flix-toteu-appointed-acting-treasurer-of-the-aas/">Dr Félix Toteu appointed acting treasurer of the AAS</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/opportunity-royal-society--dfid-africa-capacity-building-initiative/">Opportunity: Royal Society - DFID Africa Capacity Building Initiative</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/aas-senior-advisor-part-of-a-study-that-has-found-genes-that-increase-resistance-to-severe-malaria/">AAS Senior Advisor part of a study that has found genes that increase resistance to severe malaria</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/call-to-submit-articles-for-the-aas-newsletter-on-the-history-of-sciences-and-indigenous-knowledge-systems/">Call to submit articles for the AAS' newsletter on the history of sciences and indigenous knowledge systems</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/pan-african-university-calls-for-applications/">Pan African University Calls for Applications</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/obasanjo-scientific-prize/">Obasanjo Scientific Prize</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/climate-change-cop-20-outcomes/">Climate Change: COP 20 outcomes</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/encouraging-african-governments-to-increase-their-investment-in-science/">Encouraging African governments to increase their investment  in science</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/50-years-with-science-and-education-in-the-arab-north-middle-east/">50 years with Science and Education in the Arab North, Middle East</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/dfid-team-conducts-due-diligence-review-of-aas-systems/">DFID team conducts Due Diligence Review of AAS Systems</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/africa-the-origin-of-humanity-values-and-knowledge/">Africa: The origin of Humanity, values and knowledge</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/lessons-from-control-of-the-ebola-crises-impact-on-other-endemic-killer-diseases/">Lessons from Control of the Ebola crises, impact on other endemic killer diseases</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/prof-calistus-juma-how-african-innovation-can-take-on-the-world/">Prof Calistus Juma: How African innovation can take on the world</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/news/african-scientists-call-upon-their-governments-to-bridge-the-energy-gap/">African Scientists Call Upon their Governments to Bridge the Energy Gap</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/">Events</a><ul><li><a href="https://www.aasciences.ac.ke/updates/events/deltas-africa-annual-meeting-2017/">DELTAS Africa Annual Meeting 2017</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/solar-radiation-management/">Solar radiation management</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/-solar-radiation-management-srm-geoengineering-/"> Solar Radiation Management (SRM) Geoengineering </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/building-a-strong-research-ecosystem-/">Building a Strong Research Ecosystem </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/using-gene-drive-approaches-/">Using Gene Drive Approaches </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/precision-public-health-in-africa-/">Precision Public Health in Africa </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/strengthening-research-capacities-for-the-uptake-of-sustainable-agriculture-intensification/">Africa-EU Climate Change Research Platform</a></li>
	</li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/programme-and-activities-10th-ga-of-aas-/">Programme and Activities: 10th GA of AAS </a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/african-leaders-international-partners-launch-new-initiatives-to-spur-scientific-research-in-africa/">African leaders, international partners launch new initiatives to spur scientific research in Africa</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/aesa-launch-video/">AESA launch video</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/acusarima-conference-2015/">ACU-SARIMA Conference 2015</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/aas-and-partners-to-launch-aesa-the-funding-platform-for-research/">AAS and partners to launch AESA, the funding platform for research</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/aas-first-pan-african-science-olympiad/">AAS' First Pan African Science Olympiad</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/pursuing-justice-in-africa/">Pursuing Justice in Africa</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/events/islam-in-africa/">Islam in Africa</a></li>
	</ul></li>
	<li><a href="https://www.aasciences.ac.ke/updates/calendar/">Calendar</a></li>
	<li><a href="https://www.aasciences.ac.ke/updates/icasa-2015/">ICASA 2015</a></li>
	</li>
	</li>
	</li>
	</li>
	</li>
	</ul></li>
	</li>
	<li><a href="https://www.aasciences.ac.ke/alliance-for-accelerating-excellence-in-africa-aesa/">Alliance for Accelerating Excellence in Africa (AESA)</a></li>
	<li><a href="https://www.aasciences.ac.ke/thank-you/">Thank you</a></li>
	<li><a href="https://www.aasciences.ac.ke/membership-payment/">Membership payment</a></li>
	</li>
	</ul></li>
	</ul>