<ul><li><a href="http://aesa.ac.ke/aesa/">Home</a><ul><li><a href="http://aesa.ac.ke/programmes/">Programmes</a><ul><li><a href="http://aesa.ac.ke/programmes/programmes/">Programmes</a></li>
	<li><a href="http://aesa.ac.ke/programmes/aesarise-fellowship-programme/">AESA-RISE Fellowship Programme</a><ul><li><a href="http://aesa.ac.ke/programmes/aesarise-fellowship-programme/funding-opportunities/">Funding Opportunities</a></li>
	<li><a href="http://aesa.ac.ke/programmes/aesarise-fellowship-programme/news-and-events/">News and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/aesarise-fellowship-programme/news-and-events/aasaesa-announces-us2-million-investment-to-boost-africas-scientific-capacity/">AAS-AESA announces US$2 million investment to boost Africa’s scientific capacity</a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/africa-science-desk/">Africa Science Desk</a><ul><li><a href="http://aesa.ac.ke/programmes/africa-science-desk/call-for-pitches/">Call for pitches</a></li>
	<li><a href="http://aesa.ac.ke/programmes/africa-science-desk/frequently-asked-questions-asd/">Frequently Asked Questions (ASD)</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/">CIRCLE</a><ul><li><a href="http://aesa.ac.ke/programmes/circle/guidelines/">CIRCLE Open Access Publication Guidance</a></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/data-access/">Guidance for CIRCLE Visiting Fellows on Providing Access to Research Data</a></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/key-elements-of-the-circle-programme/">Key elements of the CIRCLE programme</a></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/other-publications/">Other Publications</a></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/circle-field-stories/">CIRCLE field stories</a></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/circle-news-and-events/">CIRCLE news and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/circle/circle-news-and-events/africaeu-climate-change-research-platform/">Africa-EU Climate Change Research Platform</a></li>
	<li><a href="http://aesa.ac.ke/programmes/circle/circle-news-and-events/aas-hosts-climate-change-researchers/">AAS hosts climate change researchers</a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/">Grand Challenges Africa </a><ul><li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/funding-opportunities/">Funding Opportunities</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/resources/">Resources</a><ul><li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/resources/test-forms/">Mentorship</a><ul><li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/resources/test-forms/beome-a-mentee-page/">Become a Mentee</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/resources/policies-/">Policies </a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/resources/our-innovators/">GCAiN</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/proposal-development-resources/">Proposal Development Resources</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/">News and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/dr-evelyn-gitau-featured-on-tv-talk-show-to-discuss-opportunities-in-research/">Innovation and research opportunities for the youth</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/stanford-professor-to-give-talk-at-the-aas/">Stanford professor to give talk at the AAS</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/r10-million-to-support-innovative-health-technologies-in-africa/">R10 million to support innovative health technologies in Africa</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/innovate-for-life-fund/">Innovate for Life Fund</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/precision-public-health-in-africa/">Precision Public Health in Africa</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/grant-writing-workshop-held-in-dakar-senegal/">Grant writing workshop held in Dakar, Senegal</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/study-identifies-causes-of-stunting-in-children/">Study identifies causes of stunting in children</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/grand-challenges-africa-community-meeting/">Grand Challenges Africa Community Meeting</a></li>
	<li><a href="http://aesa.ac.ke/programmes/grand-challenges-africa/events/bootcamp-workshop-for-african-innovators/">Bootcamp workshop for African innovators</a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/">DELTAS Africa</a><ul><li><a href="http://aesa.ac.ke/programmes/deltas/africa-funded-programmes/">DELTAS Africa grantees</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/funding-opportunities/">Funding Opportunities</a><ul><li><a href="http://aesa.ac.ke/programmes/deltas/funding-opportunities/past-funding-opportunities/">Past Funding Opportunities</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/">DELTAS News and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/meet-delgeme-postdoc-phd-and-msc-fellows-20162017/">Meet DELGEME Post-Doc, PhD and MSc fellows (2016-2017)</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/meeting-showcases-africas-ground-breaking-health-research/">Meeting showcases Africa’s ground breaking health research</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/deltas-africa-annual-meeting-2017/">DELTAS Africa Annual Meeting 2017</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/santhes-dr-zaza-ndhlovu-awarded-650-000-research-scholarship/">SANTHE’s Dr Zaza Ndhlovu awarded $650 000 research scholarship</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/-pioneering-research-tests-why-some-tb-bacteria-survives-treatment/"> Pioneering research tests why some TB bacteria survives treatment</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/the-art-of-science-africa-health-research-institute-hosts-an-exhibition-of-the-wellcome-image-awards-2017/">The art of science: Africa Health Research Institute hosts an exhibition of the Wellcome Image Awards 2017</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/do-hiv-patients-recover-completely-after-long-term-treatment/">Do HIV patients recover completely after long term treatment?</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/aphrc-included-in-2016-list-of-top-global-think-tanks/">APHRC included in 2016 list of top global think tanks</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/deltas-pi-appointed-headschool-of-public-health-at-wits-university/">DELTAS PI Appointed Head:School of Public Health at Wits University</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/deltas-africa-financial-reporting-workshop-in-johannesburg/">DELTAS Africa financial reporting workshop in Johannesburg</a></li>
	<li><a href="http://aesa.ac.ke/programmes/deltas/deltas-news-and-events/santhes-thumbi-ndungu-wins-28-million-gilead-grant/">SANTHE's Prof Thumbi Ndung'u wins $2.8 million Gilead grant</a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/gfgp/">Good Financial Grant Practice</a><ul><li><a href="http://aesa.ac.ke/programmes/gfgp/gfgp-news-and-events/">GFGP News and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/gfgp/gfgp-news-and-events/gfgp-technical-working-group-committee-to-meet-in-nairobi-/">GFGP Technical Working Group Committee to meet in Nairobi </a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/stem-cell-science-applications/">STEM</a><ul><li><a href="http://aesa.ac.ke/programmes/stem-cell-science-applications/stem-learning-news-and-events/">STEM Learning News and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/stem-cell-science-applications/stem-learning-news-and-events/stem-cell-science-and-applications-report/">Stem Cell Science and Applications Report</a></li>
	</ul></li>
	</ul></li>
	</li>
	<li><a href="http://aesa.ac.ke/programmes/h3africa/">Human Heredity and Health in Africa</a><ul><li><a href="http://aesa.ac.ke/programmes/h3africa/funding-opportunities/">Funding Opportunities</a><ul><li><a href="http://aesa.ac.ke/programmes/h3africa/funding-opportunities/current-calls/">Current calls</a></li>
	<li><a href="http://aesa.ac.ke/programmes/h3africa/funding-opportunities/past-calls/">Past calls</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/programmes/h3africa/guidance-notes-for-submitting-full-proposals-/">Guidance Notes for submitting full proposals </a></li>
	<li><a href="http://aesa.ac.ke/programmes/h3africa/conditions-for-applicants-for-gsk-awards/">Conditions for applicants for GSK awards</a></li>
	<li><a href="http://aesa.ac.ke/programmes/h3africa/frequently-asked-questions-for-h3africa-calls/">Frequently Asked Questions</a></li>
	<li><a href="http://aesa.ac.ke/programmes/h3africa/h3africa-news-and-events/">H3Africa News and Events</a><ul><li><a href="http://aesa.ac.ke/programmes/h3africa/h3africa-news-and-events/h3africa-webinar/">H3Africa webinar</a></li>
	</ul></li>
	</ul></li>
	</li>
	</li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/resources/">Resources</a></li>
	<li><a href="http://aesa.ac.ke/multimedia/">Multimedia</a></li>
	<li><a href="http://aesa.ac.ke/policy--advocacy/">Policy & Advocacy</a><ul><li><a href="http://aesa.ac.ke/policy--advocacy/policy--advocacy/">Policy & Advocacy</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/partners/">Partners</a><ul><li><a href="http://aesa.ac.ke/partners/overview/">Overview</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/research/">Research</a><ul><li><a href="http://aesa.ac.ke/research/research/">Research</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/cari/">CARI</a><ul><li><a href="http://aesa.ac.ke/cari/coalition-for-african-research-and-innovation/">Coalition for African Research and Innovation</a></li>
	<li><a href="http://aesa.ac.ke/cari/cari-news-and-events/">CARI News and Events</a><ul><li><a href="http://aesa.ac.ke/cari/cari-news-and-events/africas-future-depends-on-its-scientiststime-to-stop-the-brain-drain/">Africa’s future depends on its scientists.Time to stop the brain drain</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/cari/speeches/">Speeches</a><ul><li><a href="http://aesa.ac.ke/cari/speeches/ammenah-gurib-fakims-speech-at-mit/">Ammenah Gurib Fakim's speech at M.I.T</a></li>
	<li><a href="http://aesa.ac.ke/cari/speeches/president-ammenah-guribfakims-speech-at-harvard-university/">President Ammenah Gurib-Fakim's speech at Harvard University</a></li>
	<li><a href="http://aesa.ac.ke/cari/speeches/a-public-address-by-her-excellency-ameenah-guribfakim/">A public address by Her Excellency Ameenah Gurib-Fakim</a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/about/">About</a><ul><li><a href="http://aesa.ac.ke/about/overview/">About</a></li>
	<li><a href="http://aesa.ac.ke/about/leadership/">Leadership</a></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/">Activities and impact</a><ul><li><a href="http://aesa.ac.ke/about/activities-and-impact-/grand-challenges-africa-field-stories/">Grand Challenges Africa field stories</a><ul><li><a href="http://aesa.ac.ke/about/activities-and-impact-/grand-challenges-africa-field-stories/researcher-says-she-won-first-grant-after-participating-in-aesas-proposal-development-workshop/">Researcher says she won first grant after participating in AESA’s proposal development workshop</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/stem-cell-science-and-applications/">STEM cell science and applications field stories</a><ul><li><a href="http://aesa.ac.ke/about/activities-and-impact-/stem-cell-science-and-applications/kenyan-masters-graduate-finds-a-phd-scholarship-through-cbrm/">Kenyan masters graduate finds a PhD scholarship through CBRM</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/circle-field-stories/">CIRCLE field stories</a><ul><li><a href="http://aesa.ac.ke/about/activities-and-impact-/circle-field-stories/climate-change-forcing-villagers-in-tanzania-to-change-diet/">Climate change forcing villagers in Tanzania to change diet</a></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/circle-field-stories/how-participating-in-circle-has-won-one-fellow-big-grants/">How participating in CIRCLE has won one fellow big grants</a></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/circle-field-stories/circle-fellow-research-encourages-governments-to-subsidise-insurance-premiums-for-small-scale-farmers/">CIRCLE Fellow research encourages governments to subsidise insurance premiums for small scale farmers</a></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/circle-field-stories/circle-offers-opportunities-for-zimbabwean-academic-to-present-her-work-in-international-conferences/">CIRCLE offers opportunities for Zimbabwean academic to present her work in international conferences</a></li>
	<li><a href="http://aesa.ac.ke/about/activities-and-impact-/circle-field-stories/circle-provides-an-opportunity-for-a-ugandan-scientist-to-develop-his-career/">CIRCLE provides an opportunity for a Ugandan scientist to develop his career</a></li>
	</ul></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/about/news/">News</a><ul><li><a href="http://aesa.ac.ke/about/news/aas-provides-funding-to-build-africas-science-journalism-capacity/">AAS provides funding to build Africa’s science journalism capacity</a></li>
	<li><a href="http://aesa.ac.ke/about/news/african-academy-of-sciences-names-dr-tom-kariuki-interim-executive-director-/">African Academy of Sciences names Dr Tom Kariuki Interim Executive Director </a></li>
	<li><a href="http://aesa.ac.ke/about/news/aas-programme-intensifies-support-for-research-tackling-climate-change/">AAS programme intensifies support for research tackling climate change</a></li>
	<li><a href="http://aesa.ac.ke/about/news/r10-million-to-support-innovative-health-technologies-in-africa/">R10 million to support innovative health technologies in Africa</a></li>
	<li><a href="http://aesa.ac.ke/about/news/alliance-for-accelerating-excellence-in-science-in-africa-to-ignite-innovation-in-africa/">AESA to Ignite Innovation in Africa</a></li>
	<li><a href="http://aesa.ac.ke/about/news/using-gene-drive-approaches/">Using gene drive approaches</a></li>
	<li><a href="http://aesa.ac.ke/about/news/mauritian-president-supports-african-genomic-research/">Mauritian President supports African Genomic Research</a></li>
	<li><a href="http://aesa.ac.ke/about/news/centre-of-gravity-for-african-research-funding-shifts-closer-to-africa/">Centre of Gravity for African Research Funding Shifts Closer to Africa</a></li>
	<li><a href="http://aesa.ac.ke/about/news/research-boost-creates-more-opportunities-for-african-scientists/">Research boost creates more opportunities for African scientists</a></li>
	<li><a href="http://aesa.ac.ke/about/news/african-scientists-gather-for-grand-challenges-africa-meeting/">African scientists gather for Grand Challenges Africa meeting</a></li>
	<li><a href="http://aesa.ac.ke/about/news/aas-develops-a-standard-for-good-financial-grant-practice/">AAS develops a standard for Good Financial Grant Practice</a></li>
	<li><a href="http://aesa.ac.ke/about/news/aas-and-partners-to-launch-aesa-the-funding-platform-for-research/">AAS and partners to launch AESA, the funding platform for research</a></li>
	<li><a href="http://aesa.ac.ke/about/news/delgeme-launches/">DELGEME launches</a></li>
	<li><a href="http://aesa.ac.ke/about/news/afrique-oneaspire-launches/">Afrique One-Aspire launches</a></li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/about/issab-board-members/">ISSAB board members</a></li>
	</li>
	</ul></li>
	<li><a href="http://aesa.ac.ke/community-of-practice/">AESA Community of Practice</a></li>
	<li><a href="http://aesa.ac.ke/connect/">Connect</a></li>
	<li><a href="http://aesa.ac.ke/press-releases/">Press Releases</a></li>
	<li><a href="http://aesa.ac.ke/contact-info/">Contact info</a></li>
	<li><a href="http://aesa.ac.ke/reports/">Reports</a></li>
	<li><a href="http://aesa.ac.ke/other-publications/">Other publications</a></li>
	<li><a href="http://aesa.ac.ke/grant-writing-workshop/">Grant Writing Workshop</a></li>
	</li>
	</li>
	</li>
	</ul></li>
	</ul>