<table class="treeline">
			<caption>Sample table</caption>
			<thead>
				<tr>
					<th scope="col" class="preview">Preview</th>
					<th scope="col" class="pagetitle">Page title</th>
					<th scope="col" class="status">Status</th>
					<th scope="col" class="updatedon">Updated on:</th>
					<th scope="col" class="updatedby">Updated by:</th>
					<th scope="col" class="edit">Edit</th>
				</tr>
			</thead>
			<tbody>
				<? //NOTE: link titles are 100% necessary as the preview/edit link text are an accessibility problem otherwise ?>
				<tr>
					<td class="preview"><a href="#" title="Preview [Name of Page]">Preview</a></td>
					<td class="pagetitle">[Name of page]</td>
					<td class="status">Live</td>
					<td class="updatedon">03/04/07</td>
					<td class="updatedby">03/04/07</td>
					<td class="edit"><a href="#" title="Edit [Name of Page]">Edit</a></td>
				</tr>
			</tbody>
		</table>